const SOFA = 'https://api.sofascore.com/api/v1';
const CATEGORIES = [3, 6, 72, 213, 785, 871];
const BRITISH = ['Great Britain', 'United Kingdom', 'England', 'Scotland', 'Wales'];
const H = { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36', Accept: 'application/json' };
async function g(p){const r=await fetch(`${SOFA}${p}`,{headers:H});if(!r.ok)throw new Error(r.status);return r.json();}
function brit(t){const c=t?.country?.name||'';if(BRITISH.includes(c))return true;return (t?.subTeams||[]).some(s=>BRITISH.includes(s?.country?.name||''));}
function sets(s){if(!s)return'';const o=[];for(let i=1;i<=5;i++){if(typeof s[`period${i}`]==='number')o.push(s[`period${i}`]);}return o.join(' ');}
function pe(e){return{id:e.id,tournament:e.tournament?.name||'Unknown',category:e.tournament?.category?.name||'',round:e.roundInfo?.name||'',homePlayer:e.homeTeam?.name||'?',awayPlayer:e.awayTeam?.name||'?',homeCountry:e.homeTeam?.country?.name||'',awayCountry:e.awayTeam?.country?.name||'',homeScore:sets(e.homeScore),awayScore:sets(e.awayScore),homePoint:e.homeScore?.point||'',awayPoint:e.awayScore?.point||'',status:e.status?.description||'',isLive:e.status?.type==='inprogress',notStarted:e.status?.type==='notstarted',hasBritish:brit(e.homeTeam)||brit(e.awayTeam),startTimestamp:e.startTimestamp||0};}
export default async function handler(req,res){try{const cut=Math.floor(Date.now()/1000)-86400;const t=new Date().toISOString().slice(0,10);const y=new Date(Date.now()-86400000).toISOString().slice(0,10);const dates=[...new Set([t,y])];const all=[];await Promise.all(dates.flatMap(d=>CATEGORIES.map(async c=>{try{const data=await g(`/category/${c}/scheduled-events/${d}`);(data.events||[]).forEach(e=>{const m=pe(e);if(m.hasBritish&&m.startTimestamp>=cut)all.push(m);});}catch(_){}})));const seen=new Set();const u=all.filter(m=>seen.has(m.id)?false:seen.add(m.id));u.sort((a,b)=>{const r=m=>m.isLive?0:m.notStarted?1:2;if(r(a)!==r(b))return r(a)-r(b);return a.notStarted?a.startTimestamp-b.startTimestamp:b.startTimestamp-a.startTimestamp;});res.setHeader('Cache-Control','s-maxage=20, stale-while-revalidate=40');res.status(200).json(u);}catch(e){res.status(500).json({error:e.message});}}
